name: mclickdemo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.5

environment:
   sdk: '>=3.4.3 <4.0.0'
 # sdk: ^3.5.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  retrofit: ^4.0.1
  shared_preferences: ^2.0.11
  flutter_dotenv: ^5.0.2
  dio: ^5.1.2
  jwt_decoder: ^2.0.1
  infinite_scroll_pagination: ^5.0.0
  auto_route: ^10.0.1
  json_annotation: ^4.7.0
  responsive_framework: ^1.0.0
  logger: ^2.0.1
  riverpod: ^2.4.8
  flutter_riverpod: ^2.4.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.5
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.4.8
  dropdown_search: ^6.0.2
  intl: any
  trina_grid: ^1.6.9
  riverpod_annotation: ^2.3.3
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.2.0
  fl_chart: ^1.0.0
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.10
  flutter_gen: ^5.3.1
  freezed_annotation: ^3.0.0
  easy_debounce: ^2.0.3
  chunked_uploader: ^1.1.0
  file_picker: ^10.1.9
  download: ^1.0.0
  flutter_tree: ^2.0.3
  intl_utils: any
  file_saver: ^0.2.10
  percent_indicator: ^4.2.3
  flutter_credit_card:
    path: ../flutter_credit_card
  cupertino_icons: ^1.0.8
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  pdf: ^3.11.3
  web: ^1.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.0.1
  json_serializable: ^6.1.3
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  flutter_gen_runner:
  riverpod_lint: ^2.0.3
  custom_lint: ^0.7.5

flutter:
  fonts:
    # - family: MyFlutterApp
    #   fonts:
    #     - asset: assets/fonts/MyFlutterApp.ttf
    # - family: OpenSans
    #   fonts:
    #     - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
    #       weight: 400
    - family: Arial
      fonts:
        - asset: assets/fonts/arial/ARIALBD.ttf
          weight: 700
        - asset: assets/fonts/arial/ARIAL.ttf
          weight: 400

  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/env/
    - assets/icons/
flutter_intl:
  enabled: true

flutter_gen:
  output: lib/generated

